dist:
  name: otelcol-custom
  description: Custom OpenTelemetry Collector build
  output_path: /tmp/dist
extensions:
    - github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.119.0
exporters:
  - gomod: github.com/redhat-marketplace/swc-opentelemetry-collector v0.1.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0

receivers:
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/webhookeventreceiver v0.119.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.119.0
processors:
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.119.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.119.0
  - github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.119.0
