dist:
  name: otelcol-custom
  description: Custom OpenTelemetry Collector build
  output_path: /tmp/dist
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.119.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.119.0
exporters:
  - gomod: github.com/redhat-marketplace/swc-opentelemetry-collector/exporter/ibmsoftwarecentralexporter 069c9c3 
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.119.0
receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/webhookeventreceiver v0.119.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.119.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.119.0
processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.119.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.119.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.119.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.25.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.25.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.25.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.25.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.25.0

replaces:
  - github.com/redhat-marketplace/swc-opentelemetry-collector/exporter/ibmsoftwarecentralexporter => /Users/maxpaspa/swc-opentelemetry-collector/exporter/ibmsoftwarecentralexporter 
